### ISSUE TITLE
Failing due to relative path

### ISSUE THREAD

**Issue by SmileyChris** [perimosocordiae/PyCover#1]
After some investigation as to why this plugin wasn't working for me, I found that the `missing_lines.py` subprocess was raising an exception:
`NoSource: No source for code: '/opt/sublime_text/<my_relative_file_path>'`

It seems that doing `cov.analysis(relpath)` uses the current working directory to look for the file, rather than the correct location. I just changed this to use the absolute file path and it started working.

**Comment by perimosocordiae** [comment]
To be clear, do you mean that you deleted the `relpath` line and then ran `cov.analysis(fname)`?

**Comment by perimosocordiae** [comment]
Let me know if this fix worked for you. And thanks for reporting the issue!

**Comment by SmileyChris** [comment]
Cheers, I'll check it out. Looks similar to what I changed, apart from the fancy shmancy print change ;)

**Comment by perimosocordiae** [comment]
Haha, I couldn't help myself!
