### ISSUE TITLE
Screenshot of plugin in action

### ISSUE THREAD

**Issue by wldcordeiro** [perimosocordiae/PyCover#2]
I'm using this plugin but I'm not sure what to look for. Are the white arrows covered code? When I look at my coverage HTML report there's certain lines it says are covered that have the arrows next to them in Sublime. Maybe there should be three types of arrows, green = covered, red = uncovered, yellow = partial to match the HTML report.

**Comment by perimosocordiae** [comment]
I've been meaning to make a screenshot for the readme for a while now. On my setup (Ubuntu/ST3), the plugin looks like this:
![pycover_screen](https://cloud.githubusercontent.com/assets/82855/6177614/0e26d8d8-b2d6-11e4-8cda-0c5e7b097345.png)

The lines without test coverage are marked by the green arrows in the gutter.

I like your idea of matching the HTML coverage report, though. I'll look into making that happen.

**Comment by wldcordeiro** [comment]
I see, it seems that the plugin might not be working quite right for me than. I have my project running in a Vagrant VM and when I run my `coverage run --source='.' project/manage.py test` it shows up like this in the HTML report.
![screen shot 2015-02-12 at 14 48 49](https://cloud.githubusercontent.com/assets/580982/6177761/69b96d92-b2c6-11e4-9dfa-5312d744a34c.png)

But the plugin is showing every line as uncovered.

![workspace 1_002](https://cloud.githubusercontent.com/assets/580982/6177763/71434da8-b2c6-11e4-949b-ce1597359818.jpg)

I was under the impression that your plugin just generated based on the .coverage file so I thought it'd match.

**Comment by perimosocordiae** [comment]
Try asking package control to update pycover,  because I made a new release
not too long ago.

If you're on the latest version, let me know what gets printed to the
Sublime console (ctrl-`) when you toggle missing lines.
